config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources 'entries'
  
  root "welcome#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index

      @entries = Entry.all.order('created_at desc')
   end

   def new
   end

   def create
     Entry.create(entry_params)

     redirect_to entries_path
   end

   def entry_params
     params.require(:entry).permit(:title, :content)
   end

   def show
     @entry = Entry.find(params[:id])
   end

   def destroy
     @entry = Entry.find(params[:id])

     @entry.destroy
     redirect_to entries_path
   end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

    @entries = Entry.all.order('created_at desc')

    @websites = [
     ['http://railsgirls.com', 'Rails Girls'],
     ["https://en.wikibooks.org/wiki/Ruby_Programming", 'Wikibooks'],
     ["http://guides.rubyonrails.org", 'Ruby on Rails Guides']
   ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/index.html.erb
<h1>My Rails Girls Diary</h1>

<div>
  <h4><%= link_to('New Entry', new_entry_path) %></h4>
</div>

<div>
  <% @entries.each do |entry| %>
    <h2> <%= link_to(entry.title, entry_path(entry)) %> </h2>

  <% end %>
</div>

app/views/entries/new.html.erb
<h1>New entry</<h1>
  <%= form_for(Entry.new) do |form| %>
   <p><%= form.label("title") %></p>
   <%= form.text_field("title") %>
   <p><%= form.label("content") %></p>
   <%= form.text_area("content") %>
   <p><%= form.submit 'Create' %></p>
  <% end %>

app/views/entries/show.html.erb
<div>
  <h2> <%= @entry.title %> </h2>
  <p> <%= @entry.date %> </p>
  <p> <%= @entry.content %> </p>

</div>

<div>
<%= link_to('Delete', entry_path(@entry), method: :delete) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary</title>
    <title>My Little Webapp: Coding Is Magic</title>
    <meta charset="UTF-8" />
    <!-- <link rel="stylesheet" href="https://rawgithub.com/krzysztofbialek/Rails-Girls-Warsaw-App/master/style.css" /> -->
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>My Rails Girls Diary</h1>
<div>
  <% @entries.each do |entry| %>
    <h2> <%= entry.title %> </h2>
    <p> <%= entry.date %> </p>
    <p> <%= entry.content %> </p>
  <% end %>
</div>
<div>
  <h1>My favourite websites</h1>
  <ul>
    <% if @websites.empty? %>
       <%= "I will add something later" %>
    <% else %>
       <% @websites.each do |url, name| %>
         <li><a href="<%= url %>"><%= name %></a></li>
    <% end %>
   <% end %>
 </ul>
</div>
<img src="http://railsgirls.com/images/rg-warsaw.png" />